In [1]:
import numpy as np
v = np.array([1, -1, 2])
w = np.array([2, 5, 2])

In [2]:
v + w

array([3, 4, 4])

In [3]:
v - w

array([-1, -6,  0])

In [4]:
3 * v

array([ 3, -3,  6])

In [5]:
# linalg refer to Linear Algebra and norm refers to Magnitude
np.linalg.norm(v)

2.449489742783178

In [7]:
np.dot(v, w)

1

In [8]:
np.cross(v, w)

array([-12,   2,   7])

In [9]:
np.cross(w, v)

array([12, -2, -7])

In [10]:
P = np.array([[1, 7], [2, 1], [3, 2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [13]:
Q = np.array([[1, 1], [1, -1], [1, 0]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [15]:
C1 = np.add(P, Q)
print(C1)

[[2 8]
 [3 0]
 [4 2]]


In [17]:
C1 = np.subtract(P, Q)
print(C1)

[[0 6]
 [1 2]
 [2 2]]


In [18]:
R = np.array([[1, 3, 1], [1, 0, 1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [19]:
C2 = np.dot(P, R)
print(C2)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [22]:
det = np.linalg.det(C2)
print(det)

0.0


In [23]:
M = np.array([[1, -1], [2, 3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
